spring:
  kafka:
    topics:
      transaction-request: transaction-requests
      transaction-result: transaction-results
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094

    consumer:
      group-id: account-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer